[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
blur = true
dynamic_title = true
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 25
y = 20

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[keyboard]
bindings = [
{ key = "V", mods = "Control", action = "Paste" },
{ key = "C", mods = "Control", action = "Copy" },
]
