format = """
[ î‚¶](#434C5E)\
$os\
[ ïŒƒ ](bg:#434C5E fg:#1793D1)\
$username\
[î‚°](bg:#434C5E fg:#3B4252)\
$directory\
[î‚°](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[î‚°](fg:#4C566A bg:#86BBD8)\
[î‚°](fg:#86BBD8 bg:#06969A)\
[î‚°](fg:#06969A bg:#33658A)\
$python\
$docker_context\
$cmd_duration\
[î‚´](fg:#33658A)\
\n$character"""

right_format = """
[î‚¶](fg:#33658A)[ ó°£™ ](bg:#33658A)$time[î‚´](fg:#33658A)\
[ î‚¶](fg:#06969A)[ î™« ](bg:#06969A)$memory_usage[î‚´](fg:#06969A)\
"""
add_newline = true

command_timeout = 5000

[cmd_duration]
min_time = 500
format = "[ $duration ](bg:#33658A italic bright-yellow)"

[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user ]($style)'

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
#truncation_symbol = "â€¦/"
home_symbol = "î¬† "
read_only = " î‚¢"

[directory.substitutions]
"Dokumente" = "Dokumente ó°ˆ™ "
"Downloads" = "Downloads ï€™ "
"Music" = "Music ó°š "
"Bilder" = "Bilder ï€¾ "
"etc" = "etc î­¥ "
"Obsidian" = "Obsidian î€…"
"Dev" = "Dev î˜ "
"Batch" = "Batch î¯„"
"Bash" = "Bash îª… "
"Python" = "Python î˜† "
"Comics" = "Comics ó±™"
"MailArchiv" = "MailArchiv ó°¥¢"
".steam" = "Steam ï§’"
"ProtonDrive" = "ProtonDrive ï™¢"
"Docker" = "Docker ïŒˆ "

continuation_prompt = 'â–¶â–¶ '

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[nix_shell]
symbol = "ï‹œ "

[git_branch]
symbol = "ï„“"
style = "bg:#4C566A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind ]($style)'

[python]
symbol = "î˜†"
style = "bg:#33658A"
format = '[ $symbol( $version) ]($style)'

[memory_usage]
disabled = false
threshold = -1
style = "bg:#06969A"
format = "[$ram]($style)"

[status]
style = 'bg:blue'
symbol = 'ğŸ”´ '
success_symbol = 'ğŸŸ¢ SUCCESS'
not_executable_symbol = 'ğŸš«'
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "[â–ˆ](italic green)"
charging_symbol = "[â†‘](italic green)"
discharging_symbol = "[â†“](italic)"
unknown_symbol = "[â–‘](italic)"
empty_symbol = "[â–ƒ](italic red)"

[[battery.display]]
threshold = 40
style = "dimmed yellow"

[[battery.display]]
threshold = 70
style = "dimmed white"

[time]
disabled = false
time_format = "%R"
style = "bg:#33658A"
format = '[ $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[  ó±©](bold fg:color_green)'
#error_symbol = '[ï²](bold fg:color_red)'
error_symbol = "[âœ—](bold red)"
